name: JMeter Performance Tests

run-name: JMeter - ${{ github.event.inputs.test_type }}

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: "Escolha o tipo de teste para executar"
        required: true
        default: "carga"
        type: choice
        options:
          - carga
          - pico

jobs:
  performance-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          sudo tar -xzf apache-jmeter-5.6.3.tgz -C /opt
          rm apache-jmeter-5.6.3.tgz
      
      - name: Run JMeter Test
        run: |
          /opt/apache-jmeter-5.6.3/bin/jmeter.sh -n -t ./blazedemo.jmx \
          -Jthreads_carga=${{ github.event.inputs.test_type == 'load-test' && 250 || 0 }} \
          -Jthreads_pico=${{ github.event.inputs.test_type == 'spike-test' && 250 || 0 }} \
          -l results-${{ github.event.inputs.test_type }}.jtl -e -o logs

      - name: Upload Results JTL (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-jtl
          path: results-${{ github.event.inputs.test_type }}.jtl

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload HTML Report to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./logs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
