name: JMeter Performance Tests

run-name: JMeter - ${{ github.event.inputs.test_type }}

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: "Escolha o tipo de teste para executar"
        required: true
        default: "load-test"
        type: choice
        options:
          - load-test
          - spike-test

jobs:
  performance-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run JMeter via Docker
        run: |
          THREADS_CARGA=0
          THREADS_PICO=0
      
          if [ "${{ github.event.inputs.test_type }}" = "load-test" ]; then
            THREADS_CARGA=250
          else
            THREADS_PICO=250
          fi
      
          docker run --rm \
            -v ${{ github.workspace }}:/test \
            -w /test \
            justb4/jmeter:5.6.3 \
            -n -t blazedemo.jmx \
            -Jthreads_carga=$THREADS_CARGA \
            -Jthreads_pico=$THREADS_PICO \
            -l results-${{ github.event.inputs.test_type }}.jtl \
            -e -o logs

      - name: Upload Results JTL (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-jtl
          path: results-${{ github.event.inputs.test_type }}.jtl

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload HTML Report to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./logs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
